### ISSUE TITLE
npmName.many error

### ISSUE THREAD

**Issue by ZYSzys** [sindresorhus/npm-name#29]
Refs: https://github.com/sindresorhus/npm-name-cli/issues/16

When an error happening, all the others results missed.

```js
const npmName = require('npm-name');

(async () => {
  try {
    await npmName.many(['sdhd','_ABC', 'chalk']);
  } catch (error) {
    console.log(error.message);
    // Invalid package name: _ABC
    // - name cannot start with an underscore
    // - name can no longer contain capital letters
  }
})();
```

One way I thought to fix it is `return error` instead of `throw error` when validating name, and then we check the result(`true` or `false` or `instanceof Error`) in other modules.
@sindresorhus how do you think, is it reasonable for you ?

**Comment by sindresorhus** [comment]
You could use https://github.com/sindresorhus/p-settle instead of `Promise.all` and then throw an https://github.com/sindresorhus/aggregate-error error if there were any errors. Alternatively, you could add an optional to https://github.com/sindresorhus/p-map to only throw an aggregate error at the end.
